# Generated by Django 6.0.6 on 2026-06-22 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='job_seekers/profile_images/')),
                ('full_name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, null=True)),
                ('education', models.TextField(blank=True, null=True)),
                ('cv_file', models.FileField(blank=True, null=True, upload_to='job_seekers/cvs/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
