# Generated by Django 6.0.6 on 2026-06-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_company_company_name_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='business_license',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_info',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
