# Generated by Django 6.0.6 on 2026-06-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_company_business_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='companies/business_licenses/'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
