# Generated by Django 6.0.6 on 2026-06-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_otp_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
    ]
